[tool.poetry]
name = "llama-parser"
version = "0.1.2"
description = "Parse files into RAG-Optimized formats."
authors = ["Logan Markewich <logan@llamaindex.ai>"]
license = "MIT"
readme = "README.md"
packages = [{include = "llama_parser"}]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
llama-index = "^0.9.40"


[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
